### PR TITLE
NPR One player does not have a play/pause button

### PR DESCRIPTION
**Pull request by pwnb0t**
It has individual play and pause buttons rather than a single button.

### CODE REVIEW

**Comment by pwnb0t** [comment]
Correct me if I'm wrong, but I think if it has two individual button, then it should only have the 'play' and 'pause' properties and not the playPause property. Right now, pressing play will start the stream but pressing play again won't stop the stream.

**Comment by berrberr** [comment]
Interesting, this is actually a unique case. Great job NPR!

They have two seperate buttons `a.play` and `a.pause`. The only way AFAIKT to see if it's playing is to see if `a.pause` is visible (by default/when player is not playing it has `display: none`). 

This means another clause will have to be added to `BaseController#isPlaying`. There is a style check in there but it is only for *play* buttons (since some players will hide the play button when the player is playing - this makes some sense). What NPR player is doing is a little backwards - they are only showing the pause button if the player is playing & overlaying that button on top of the play button and not hiding the play element!

I will add this, thanks for the info!

**Comment by pwnb0t** [comment]
I see you have now put in the proper fix in 1.4.9. Thanks!

**Comment by berrberr** [comment]
Yes! Fixed in 1.4.9 :+1:

**Pull request closed without merging**
