### PR TITLE
rdio closed

### PR DESCRIPTION
**Pull request by tobeorla**
On November 16, 2015, Rdio filed for chapter 11 bankruptcy in which they had to pay $200 million and announced the sale of certain intellectual property to Pandora Radio.[6] The purchase price is $75 million in cash
https://en.wikipedia.org/wiki/Rdio

### CODE REVIEW

**Comment by Palivonas** [comment]
Shouldn't it be removed from Sitelist.js as well?

**Comment by berrberr** [comment]
@tobeorla Thanks -- also needs to be removed from `Sitelist.js` as @Palivonas said

**Comment by tobeorla** [comment]
Done :)

**Comment by berrberr** [comment]
Thanks :)

**Pull request merged**
