### PR TITLE
Use youtube video default thumbnail for art

### PR DESCRIPTION
**Pull request by bsinky**
Using the information from [this StackOverflow answer](https://stackoverflow.com/a/2068371/4276832), adds art for Youtube by pulling the default thumbnail for the playing video.

### CODE REVIEW

**Comment by nemchik** [comment]
I like this, but I was wondering how to make this idea more reusable and I came up with this;

```
controller.getArtData = function() {

  function getParameterByName(name, url) {
    if (!url) {
      url = window.location.href;
    }
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
      results = regex.exec(url);
    if (!results) {
      return null;
    }
    if (!results[2]) {
      return '';
    }
    return decodeURIComponent(results[2].replace(/\+/g, " "));
  }
  
  var vid = getParameterByName('v');
  if (vid !== null) {
    return "https://img.youtube.com/vi/" + vid + "/default.jpg";
  }
  return null;

};
```

The `getParameterByName` function is something I found here https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript and could easily be included elsewhere making it usable by other controllers or for other purposes.

**Comment by bsinky** [comment]
Hey @nemchik, thanks for the suggestion!

On reading more of the answers from the StackOverflow question you linked, I think [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) should work in this case, with the benefit that it's already built into the browser.

The only reason I can think that URLSearchParams wouldn't be useable is if Streamkeys needs to support versions of Chrome older than Chrome 49 (when URLSearchParams was first implemented).  I'm guessing this isn't an issue though?

**Comment by nemchik** [comment]
@bsinky I like `URLSearchParams`. That would be very short and sweet. I don't think it's all that common for people to disable chrome's auto updates.

Here is a much shorter rewrite;

```
controller.getArtData = function() {

  let params = (new URL(location)).searchParams;
  
  var vid = params.get('v');
  if (vid !== null) {
    return "https://img.youtube.com/vi/" + vid + "/default.jpg";
  }
  return null;

};
```

**Comment by nemchik** [comment]
This looks good now. Nice and clean!

**Comment by berrberr** [comment]
Looks good! Thanks @bsinky @nemchik

**Pull request merged**
