### PR TITLE
TwitchController fix for redesign

### LINKED ISSUE #534: Twitch no longer working
It seems this add-on no longer works with Twitch after the redesign they did recently. 

> TwitchController.js:1 STREAMKEYS-ERROR: Element not found for click. .qa-pause-play-button

This selector will find the current button "button[data-a-target='player-play-pause-button']".

### PR DESCRIPTION
**Pull request by HLK65**
Fixes #534 (Play/Pause functionality), song (title) and isPlaying.

I've seen the pr #541 of @jfb74 but I think using the attribute selector is the way to go in this case and I fixed the other issues as well. ( #Fixes #541 )

@jfb74 maybe you can validate, since I can't test it right now. 
Otherwise everybody can test this, just go to twitch.tv, select a live stream (go to the channel) and check that play/pause, play/pause status and title is working.

Known issues: 
* Overlay player not supported
* Landing page not supported 

For now I've created a **_hotfix_ using Tampermonkey**: https://github.com/HLK65/TwitchRedesignStreamkeysHotfix/blob/master/script.js

### CODE REVIEW

**Comment by TheBSGamer** [comment]
How do I apply this hotfix? Do I need to build it the same way you would as the master? I'm new to this whole thing.

**Comment by TheBSGamer** [comment]
> How do I apply this hotfix? Do I need to build it the same way you would as the master? I'm new to this whole thing.

Nevermind, I figured it out. Those that are trying to figure this out, download Tampermonkey from Chrome Web Store and paste this script in as a new script.

Thanks @HLK65! It works perfectly!

**Comment by HLK65** [comment]
updated the script to work when page is loading slowly and to apply the fix whenever the url changes

**Comment by berrberr** [comment]
Using this in favor of #541 . Thanks!

**Pull request merged**
