### PR TITLE
Npm updates

### PR DESCRIPTION
**Pull request by nemchik**
Tried to rebuild my `node_modules` folder and had trouble without updating dependencies. Once I got it working jshint gave me errors from `code/js/controllers/CastboxController.js` so I have resolved the linting issues with that.

### CODE REVIEW

**Comment by nemchik** [comment]
I've just merged some changes to this branch that also address Travis not building. I've replaced PhantomJS with Chromium and updated a few more packages as well as the node_js version Travis was using from 6 to 11.

**Comment by nemchik** [comment]
I've got further updates I've almost finished, based heavily on @cubimon 's #476 PR. Most of the updates are about lodash, but there's additional cleanup of the phantomjs leftovers.

I can't get builds to pass https://travis-ci.com/nemchik/streamkeys/builds/125166586 I'm a bit lost on fixing that one issue.

Here is the commit with the differences between this PR and the build linked https://github.com/nemchik/streamkeys/commit/7433576e844c19c41a6f31320f766f7d2f8cc5a0

I'm open to any ideas.

**Comment by nemchik** [comment]
Ok a quick update on my comment above; here's a new commit that gets builds to pass https://github.com/nemchik/streamkeys/commit/4c07df5810e9789d42b920a7deb2b7e65d26e843 but I am not 100% confident that it's doing what is actually desired here. I tried my best to make sense of what's supposed to be happening and I think the idea is for `site.alias` to not include anything from `attributes.removedAlias`. Can anyone confirm this makes sense? If so I'll merge that branch into this one so this PR can include the additional changes.

**Comment by nemchik** [comment]
Also made some progress and wanted to highlight this https://github.com/nemchik/streamkeys/pull/5 because it fixes the only critical vulnerabilities in the dependencies.

**Comment by nemchik** [comment]
Ok so really as long as someone is able to confirm that I've got https://github.com/nemchik/streamkeys/commit/4c07df5810e9789d42b920a7deb2b7e65d26e843 right I'll merge https://github.com/nemchik/streamkeys/pull/6 into this branch.

**Comment by cubimon** [comment]
`npm test` gives me three errors: 

```
> karma start --single-run

Deprecated private createPreprocessor() API
31 08 2019 21:29:01.749:INFO [framework.browserify]: bundle built
31 08 2019 21:29:01.847:INFO [karma-server]: Karma v4.3.0 server started at http://0.0.0.0:9876/
31 08 2019 21:29:01.858:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
31 08 2019 21:29:01.957:INFO [launcher]: Starting browser ChromeHeadless
31 08 2019 21:29:05.996:INFO [HeadlessChrome 77.0.3844 (Windows 10.0.0)]: Connected on socket eoEJ20YEXOVXvQkXAAAA with id 89438196
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: 'Basic Music Site', selectors: Object{playPause: null, play: '#play', pause: '#pause', playNext: '#play-next', playPrev: '#play-prev', mute: '#volume', like: '#like', dislike: '#dislike', iframe: null, playState: '#player-container.playing', song: '#song-title', artist: '#artist-title', album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: false}

  base controller
    basic music site
      ✓ gets proper state data on init
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ plays and pauses and updates player state
LOG LOG: 'STREAMKEYS-INFO: playNext', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ plays next and updates player state
LOG LOG: 'STREAMKEYS-INFO: playPrev', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ plays prev and updates player state
LOG LOG: 'STREAMKEYS-INFO: mute', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ mutes
LOG LOG: 'STREAMKEYS-INFO: like', ''
      ✓ likes
LOG LOG: 'STREAMKEYS-INFO: dislike', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ dislikes
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: 'Hideplayer Music Site', selectors: Object{playPause: null, play: null, pause: null, playNext: null, playPrev: null, mute: null, like: null, dislike: null, iframe: null, playState: null, song: null, artist: null, album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: false}
    music site with hideplayer
      ✓ sets hidePlayer
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: 'Music Site With iFrame', selectors: Object{playPause: null, play: '#play', pause: '#pause', playNext: '#play-next', playPrev: null, mute: null, like: null, dislike: null, iframe: '#player-frame', playState: '#play.playing', song: '#song-title', artist: null, album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: false}
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
    music site with iframe
      ✓ gets proper state data on init
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
      ✓ plays and pauses and updates player state
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: 'Music Site With Buttonswitch', selectors: Object{playPause: null, play: '.playBtn', pause: '.pauseBtn', playNext: null, playPrev: null, mute: null, like: null, dislike: null, iframe: null, playState: null, song: null, artist: null, album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: true}
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
    music site with buttonSwitch
      ✓ plays and pauses and updates player state
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: 'Music Site With playPause and playState', selectors: Object{playPause: '#playpause', play: null, pause: null, playNext: null, playPrev: null, mute: null, like: null, dislike: null, iframe: null, playState: '#player-container.playing', song: null, artist: null, album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: false}
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: playPause', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
    music site with playPause button and playState
      ✓ plays and pauses and updates player state
LOG LOG: 'STREAMKEYS-INFO: Attached listener for ', BaseController{siteName: null, selectors: Object{playPause: '#pause', play: null, pause: null, playNext: null, playPrev: '#prev', mute: '#muteB', like: null, dislike: null, iframe: null, playState: null, song: null, artist: null, album: null, art: null, currentTime: null, totalTime: null}, oldState: Object{}, buttonSwitch: false}
    music site with alternating playPause selector
      ✓ plays and pauses and updates player state

  sitelist
    ✓ matches the correct controller for site url
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
LOG LOG: 'STREAMKEYS-INFO: Player state change', ''
    ✓ creates a list of sites
    ✗ matches valid site urls
        Uncaught TypeError: Cannot read property 'tagName' of null thrown

    ✓ doesn't match invalid site urls
    ✓ gets site name from valid url
    ✓ gets default controller name from valid url
    ✓ gets custom controller name from valid url
    ✓ matches aliases
    ✓ gets controller name from aliased urls
    ✓ doesn't get wrong controller from alias
    ✓ doesn't match blacklisted domains
    ✓ toggles site aliases
    ✗ matches ip aliases
        Uncaught TypeError: Cannot read property 'tagName' of null thrown

    ✓ gets music tabs from chrome tabs
    ✓ gets active music tabs when all are active
    ✓ toggles enable/disable of a tab
    ✓ toggles enable/disable of a site

  loading settings from chrome.storage.sync
    loading v0 settings
      ✗ creates properly structured storage object
        Uncaught TypeError: Cannot read property 'tagName' of null thrown

      ✓ marks enabled states on sitelsit
    loading v1 settings with missing and undefined sites
      ✓ creates properly structured storage object
      ✓ marks enabled states on sitelsit
      ✓ sets aliases properly

  site priority
    ✓ sets priority
    ✓ only returns tabs with highest priority
    ✓ doesn't affect site enabled state
    ✓ doesn't affect tab enabled state
    ✗ doesn't overwrite settings on priority update
        Uncaught TypeError: Cannot read property 'tagName' of null thrown


HeadlessChrome 77.0.3844 (Windows 10.0.0): Executed 40 of 40 (4 FAILED) (3.413 secs / 0 secs)
TOTAL: 4 FAILED, 36 SUCCESS


1) matches valid site urls
     sitelist
     Uncaught TypeError: Cannot read property 'tagName' of null thrown

2) matches ip aliases
     sitelist
     Uncaught TypeError: Cannot read property 'tagName' of null thrown

3) creates properly structured storage object
     loading settings from chrome.storage.sync loading v0 settings
     Uncaught TypeError: Cannot read property 'tagName' of null thrown

4) doesn't overwrite settings on priority update
     site priority
     Uncaught TypeError: Cannot read property 'tagName' of null thrown


npm ERR! Test failed.  See above for more details.
```

**Comment by nemchik** [comment]
I've seen these errors on and off inconsistently while getting the builds to work. If you know how to track down the fix those issues I'll gladly accept PRs to the https://github.com/nemchik/streamkeys/tree/more-npm branch before merging https://github.com/nemchik/streamkeys/pull/6

**Comment by cubimon** [comment]
I had the same issue in my fork, tests ran in random order. Try this in karma config:
```js
client: {
      jasmine: {
        random: false
      }
    }
```

**Comment by nemchik** [comment]
Done. Build passed. Hopefully that resolves the issue permanently.

**Comment by nemchik** [comment]
Any feedback on https://github.com/nemchik/streamkeys/commit/4c07df5810e9789d42b920a7deb2b7e65d26e843 is still welcome.

**Comment by cubimon** [comment]
I guess the whole [nemchik@npm-updates](https://github.com/nemchik/streamkeys/tree/npm-updates) branch, since commit 4c07df5 contains only a single small change. Or is you question if difference is the new xor?

**Comment by nemchik** [comment]
https://github.com/nemchik/streamkeys/tree/npm-updates is the branch for this commit.

https://github.com/nemchik/streamkeys/pull/6 is the changes between https://github.com/nemchik/streamkeys/tree/npm-updates and https://github.com/nemchik/streamkeys/tree/more-npm


I'm pretty confident with everything in https://github.com/nemchik/streamkeys/tree/more-npm except https://github.com/nemchik/streamkeys/commit/4c07df5810e9789d42b920a7deb2b7e65d26e843 I'm not positive is correct. Without that change builds were failing due to being unable to remove the test alias.

**Comment by cubimon** [comment]
I still have `xor` on my branch, but `difference` makes much more sense from the variable names, since `removedAlias` should be removed instead of added, if it is not in the alias list.

**Comment by nemchik** [comment]
That's what I thought. I'll go ahead and merge it. If @berrberr has any feedback I'll adjust as needed.

**Comment by nemchik** [comment]
Merged in a commit to fix all `npm outdated` packages. Builds still passing. `sinon-chrome` was the only annoying part here so i've done it using `karma-sinon-chrome`.

**Comment by berrberr** [comment]
This is really great. Much needed update! Thanks @nemchik 😄

**Pull request merged**
