### PR TITLE
Fix prev button for PocketCasts

### PR DESCRIPTION
**Pull request by taschmidt**

### CODE REVIEW

**Comment by nemchik** [comment]
The other selectors in this controller seem to use underscores. Are they still correct?

**Comment by taschmidt** [comment]
Yep, they seem to be kind of "in between" schemes. The "skip forward" button actually has both classes "skip_forward_button" AND "skip-forward-button". I changed that one to hopefully future proof it a little.

I did notice the mute selector appears to be wrong but I can't find a mute button in the extension?

**Comment by nemchik** [comment]
Thanks for the additional look!

**Comment by taschmidt** [comment]
@nemchik how often do you do releases to the Chrome store? Just curious so I can stop running my local dev version! 😆

**Comment by nemchik** [comment]
@berrberr actually does that 😄 It'll be up to him. I just try to help out in the repo.

**Comment by taschmidt** [comment]
Oh, sorry!

**Pull request merged**
