### PR TITLE
Version 1.8.0

### PR DESCRIPTION
**Pull request by berrberr**
Small fixes and version bump

### CODE REVIEW

**Comment by cubimon** [comment]
if you update lodash, you may take a look my changes [here](https://github.com/cubimon/streamkeys/commit/0f1103cbec7379d9e5838017dc25f7e08abbc5e3) and [here](https://github.com/cubimon/streamkeys/commit/60ad17559036cff12cf30d952fa7b5f03fbb3f67), which contain some lodash api changes.

**Comment by berrberr** [comment]
@cubimon thanks so much that is super helpful, exactly what I was looking for! 

Also I haven't forgotten about your PR 😅. Just wanted to push out this version since it's been a while and have been too busy to do proper review. Soon!

**Comment by citizensas** [comment]
Is it really necessary to have upgraded `lodash` in `streamkeys@1.8.0`?

**Comment by berrberr** [comment]
Stale, will re-open

**Pull request closed without merging**
