### PR TITLE
Fixing Spotify compatibility

### PR DESCRIPTION
**Pull request by aadfPT**
Spotify uses the icon size in the class name, and it doesn't always match.
I have changed the selectors to go for the title instead.

### CODE REVIEW

**Comment by aadfPT** [comment]
Saw in issue #286 that it's localized and therefore won't work for all users.

**Comment by aadfPT** [comment]
Now has alternative selectors that use the class name but ignore the size tag.

**Comment by aadfPT** [comment]
The build error has nothing to due with my changes to the code.

**Comment by berrberr** [comment]
Didn't realize that they also changed the icon size in classname too 😟 

This seems like a good workaround. Thank you!

**Pull request merged**
