### PR TITLE
add youtube music controller

### PR DESCRIPTION
**Pull request by post-l**
Support for YouTube Music.
https://music.youtube.com/

### CODE REVIEW

**Comment by post-l** [comment]
`es6-promise` is a direct dependency. It should be added back to fix the build.
```
[framework.browserify]: Error: Cannot find module 'es6-promise' from '/home/travis/build/berrberr/streamkeys/code/js/modules'
```
It was remove by the commit: https://github.com/berrberr/streamkeys/commit/4d0ab2a8ad0c4dae0f7a99d3e5ca29eb65d4f99c

It is used in `background.js` and `Sitelist.js`
https://github.com/berrberr/streamkeys/blob/8622cdc79e1ff3ba53a43c430e01d73f0b79d68d/code/js/background.js#L7-L11

**Comment by leocaseiro** [comment]
@post-l perhaps if you add `es6-promise` to the `package.json` `devDependencies`, the build will pass.

**Comment by lleites** [comment]
Looking forward for this!

**Comment by berrberr** [comment]
Thanks for this & fixing the build!

**Pull request merged**
