### PR TITLE
Fix Spotify controller

### LINKED ISSUE #771: Spotify Web Player Issues
SteamKeys has stopped working with Spotify Web Player.

### PR DESCRIPTION
**Pull request by evilarceus**
Fixes #771

### CODE REVIEW

**Comment by impbob** [comment]
This works for me on Chrome 91.0.4472.77 (64-bit) when visiting https://open.spotify.com/

**Comment by dimsanchuk** [comment]
Is this project alive? Spotify users are waiting for this fix.

**Comment by RomanBorets** [comment]
I wrote to author on email a couple weeks ago, but nothing happens.

**Comment by Jikeh** [comment]
Built it and it doesn't seem to work for me with Spotify. Running Chrome 92.0.4515.107 (64-bit)

**Comment by RomanBorets** [comment]
> Built it and it doesn't seem to work for me with Spotify. Running Chrome 92.0.4515.107 (64-bit)

Have same version Chrome - all works fine. What exactly not working? Did u set up hot-keys?

**Comment by Jikeh** [comment]
> Have same version Chrome - all works fine. What exactly not working? Did u set up hot-keys?

_Play/Pause_ command doesn't work for me, while _Previous_ works. I did set up the hot-keys, but the streamkeys interface button doesn't work either, so it doesn't look like a hot-keys problem. Not sure what I'm missing, guess I'll try to rebuild it later and see how it goes.

**Comment by berrberr** [comment]
Thanks @evilarceus for the fix! Sorry for delays

**Comment by Voidheartd** [comment]
> Thanks @evilarceus for the fix! Sorry for delays

Will this be pushed out to the chrome store sometime soon?

**Pull request merged**
