### PR TITLE
Added Apple Music Beta support.

### PR DESCRIPTION
**Pull request by dhrivnak**
Also fixed syntax in PluralsightController.

### CODE REVIEW

**Comment by dhrivnak** [comment]
Just wanted to add a note that the URL for this will likely change when Apple's online music player goes out of beta. I hope that's OK!

**Comment by berrberr** [comment]
Thanks 👍

**Comment by dhrivnak** [comment]
No problem! Thanks for making this plugin and for making it so easy to extend. Great work dude.

**Comment by berrberr** [comment]
@dhrivnak no problem, glad it was easy! 👍

**Pull request merged**
