### PR TITLE
Beautify everything

### PR DESCRIPTION
**Pull request by nemchik**
Using https://github.com/Glavin001/atom-beautify for beautifier and the following linters:
https://github.com/steelbrain/linter
https://github.com/AtomLinter/linter-csslint
https://github.com/AtomLinter/linter-htmlhint
https://github.com/AtomLinter/linter-jshint
https://github.com/sirbrillig/linter-mixed-indent

This cleans everything up nicely. In my testing I confirmed nothing functional or visual has changed from an end user experience. These changes are strictly for developers and code cleanliness.

### CODE REVIEW

**Comment by nemchik** [comment]
P.S. I ran all of this on every file that was not minified. All minified files were untouched.

**Comment by nemchik** [comment]
Another note:
The tools I listed are not required for future development. Those are just the things I used to ensure that everything was consistent and standard.

**Comment by nemchik** [comment]
It looks like this has gone a bit stale. I can rebase it if you'd like. Or if you'd prefer not move forward with this idea I can close this PR.

**Comment by berrberr** [comment]
Thanks for the effort @nemchik. Let's hold off on this for now, too many changes happening :)

**Pull request closed without merging**
