### PR TITLE
Update Spotify controller

### PR DESCRIPTION
**Pull request by nemchik**
Use class selectors in Spotify

I wasn't sure how to reopen https://github.com/berrberr/streamkeys/pull/320 but I confirmed that in 1.7.0 the issue still exists. This solves https://github.com/berrberr/streamkeys/issues/355

### CODE REVIEW

**Comment by berrberr** [comment]
Spotify works for me with 1.7.0

Looking at the selectors here the difference between what we have now:

`".now-playing-bar button[class*=play]"`

and what you added

`".control-button.spoticon-play-16"`

is the `.now-playing-bar` parent element. Does your version of the spotify web player not have that element? Otherwise the selectors are functionally equivalent. I can confirm that the buttons on the working player also contain the `.control-button` class

**Comment by nemchik** [comment]
I'll be able to test tomorrow, but I don't think the player controls were the issue, it was the artist and song that were the problem. Might just want to confirm we have all the right buttons working (again I can check that tomorrow, and I'll keep the old selectors if possible).

Also I don't think Spotify is in the middle of any kind of transition to a new player at the moment, so the multi select and lodash stuff shouldn't be needed.

**Comment by nemchik** [comment]
Ok, I have changed my commit around after some investigating and testing. The `.now-playing-bar` seems to be a pretty safe bet to use with the current player (I had overlooked this with my original commit). I now have all the buttons working, and the proper song and artist selectors.

**Comment by berrberr** [comment]
Looks good now. Thanks :)

**Pull request merged**
